### ISSUE TITLE
Exception when using remainder operation (modulus)

### ISSUE THREAD

**Issue by yasharrashedi** [psycho-ir/mr-hashemi#9]
Here is my code 

```
bebin main() {
	i = 2;
	age(i % 2 == 0) bood{
	    bechap("zoj");
	} na? {
	    bechap("fard");
	}
}
```

everything seems normal according to the documentation we can use java arithmetic operators, but in case of using remainder operator, program stops with following exception

```
org.graalvm.polyglot.PolyglotException: java.util.UnknownFormatConversionException: Conversion = '''
	at java.util.Formatter.checkText(Formatter.java:2579)
	at java.util.Formatter.parse(Formatter.java:2565)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at ninja.soroosh.hashem.lang.parser.HashemLanguageParser.throwParseError(HashemLanguageParser.java:132)
	at ninja.soroosh.hashem.lang.parser.HashemLanguageParser.access$000(HashemLanguageParser.java:27)
	at ninja.soroosh.hashem.lang.parser.HashemLanguageParser$BailoutErrorListener.syntaxError(HashemLanguageParser.java:119)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Lexer.notifyListeners(Lexer.java:364)
	at org.antlr.v4.runtime.Lexer.nextToken(Lexer.java:144)
	at org.antlr.v4.runtime.BufferedTokenStream.fetch(BufferedTokenStream.java:169)
	at org.antlr.v4.runtime.BufferedTokenStream.sync(BufferedTokenStream.java:152)
	at org.antlr.v4.runtime.BufferedTokenStream.consume(BufferedTokenStream.java:136)
	at org.antlr.v4.runtime.Parser.consume(Parser.java:571)
	at org.antlr.v4.runtime.Parser.match(Parser.java:203)
	at ninja.soroosh.hashem.lang.parser.HashemLanguageParser.factor(HashemLanguageParser.java:974)
	at ninja.soroosh.hashem.lang.parser.HashemLanguageParser.term(HashemLanguageParser.java:895)
	at ninja.soroosh.hashem.lang.parser.HashemLanguageParser.arithmetic(HashemLanguageParser.java:827)
	at ninja.soroosh.hashem.lang.parser.HashemLanguageParser.logic_factor(HashemLanguageParser.java:765)
	at ninja.soroosh.hashem.lang.parser.HashemLanguageParser.logic_term(HashemLanguageParser.java:707)
	at ninja.soroosh.hashem.lang.parser.HashemLanguageParser.expression(HashemLanguageParser.java:649)
	at ninja.soroosh.hashem.lang.parser.HashemLanguageParser.if_statement(HashemLanguageParser.java:542)
	at ninja.soroosh.hashem.lang.parser.HashemLanguageParser.statement(HashemLanguageParser.java:411)
	at ninja.soroosh.hashem.lang.parser.HashemLanguageParser.block(HashemLanguageParser.java:320)
	at ninja.soroosh.hashem.lang.parser.HashemLanguageParser.function(HashemLanguageParser.java:267)
	at ninja.soroosh.hashem.lang.parser.HashemLanguageParser.hashemlanguage(HashemLanguageParser.java:175)
	at ninja.soroosh.hashem.lang.parser.HashemLanguageParser.parseHashemiLang(HashemLanguageParser.java:145)
	at ninja.soroosh.hashem.lang.HashemLanguage.parse(HashemLanguage.java:71)
	at com.oracle.truffle.api.TruffleLanguage$ParsingRequest.parse(TruffleLanguage.java:833)
	at com.oracle.truffle.api.TruffleLanguage.parse(TruffleLanguage.java:1245)
	at com.oracle.truffle.api.LanguageAccessor$LanguageImpl.parse(LanguageAccessor.java:208)
	at com.oracle.truffle.polyglot.PolyglotSourceCache.parseImpl(PolyglotSourceCache.java:92)
	at com.oracle.truffle.polyglot.PolyglotSourceCache.parseCached(PolyglotSourceCache.java:73)
	at com.oracle.truffle.polyglot.PolyglotLanguageContext.parseCached(PolyglotLanguageContext.java:321)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:820)
	at org.graalvm.polyglot.Context.eval(Context.java:344)
	at ninja.soroosh.hashem.lang.launcher.HashemiMain.executeSource(HashemiMain.java:65)
	at ninja.soroosh.hashem.lang.launcher.HashemiMain.main(HashemiMain.java:46)
Original Internal Error: 
java.util.UnknownFormatConversionException: Conversion = '''
	at java.util.Formatter.checkText(Formatter.java:2579)
	at java.util.Formatter.parse(Formatter.java:2565)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at ninja.soroosh.hashem.lang.parser.HashemLanguageParser.throwParseError(HashemLanguageParser.java:132)
	at ninja.soroosh.hashem.lang.parser.HashemLanguageParser.access$000(HashemLanguageParser.java:27)
	at ninja.soroosh.hashem.lang.parser.HashemLanguageParser$BailoutErrorListener.syntaxError(HashemLanguageParser.java:119)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Lexer.notifyListeners(Lexer.java:364)
	at org.antlr.v4.runtime.Lexer.nextToken(Lexer.java:144)
	at org.antlr.v4.runtime.BufferedTokenStream.fetch(BufferedTokenStream.java:169)
	at org.antlr.v4.runtime.BufferedTokenStream.sync(BufferedTokenStream.java:152)
	at org.antlr.v4.runtime.BufferedTokenStream.consume(BufferedTokenStream.java:136)
	at org.antlr.v4.runtime.Parser.consume(Parser.java:571)
	at org.antlr.v4.runtime.Parser.match(Parser.java:203)
	at ninja.soroosh.hashem.lang.parser.HashemLanguageParser.factor(HashemLanguageParser.java:974)
	at ninja.soroosh.hashem.lang.parser.HashemLanguageParser.term(HashemLanguageParser.java:895)
	at ninja.soroosh.hashem.lang.parser.HashemLanguageParser.arithmetic(HashemLanguageParser.java:827)
	at ninja.soroosh.hashem.lang.parser.HashemLanguageParser.logic_factor(HashemLanguageParser.java:765)
	at ninja.soroosh.hashem.lang.parser.HashemLanguageParser.logic_term(HashemLanguageParser.java:707)
	at ninja.soroosh.hashem.lang.parser.HashemLanguageParser.expression(HashemLanguageParser.java:649)
	at ninja.soroosh.hashem.lang.parser.HashemLanguageParser.if_statement(HashemLanguageParser.java:542)
	at ninja.soroosh.hashem.lang.parser.HashemLanguageParser.statement(HashemLanguageParser.java:411)
	at ninja.soroosh.hashem.lang.parser.HashemLanguageParser.block(HashemLanguageParser.java:320)
	at ninja.soroosh.hashem.lang.parser.HashemLanguageParser.function(HashemLanguageParser.java:267)
	at ninja.soroosh.hashem.lang.parser.HashemLanguageParser.hashemlanguage(HashemLanguageParser.java:175)
	at ninja.soroosh.hashem.lang.parser.HashemLanguageParser.parseHashemiLang(HashemLanguageParser.java:145)
	at ninja.soroosh.hashem.lang.HashemLanguage.parse(HashemLanguage.java:71)
	at com.oracle.truffle.api.TruffleLanguage$ParsingRequest.parse(TruffleLanguage.java:833)
	at com.oracle.truffle.api.TruffleLanguage.parse(TruffleLanguage.java:1245)
	at com.oracle.truffle.api.LanguageAccessor$LanguageImpl.parse(LanguageAccessor.java:208)
	at com.oracle.truffle.polyglot.PolyglotSourceCache.parseImpl(PolyglotSourceCache.java:92)
	at com.oracle.truffle.polyglot.PolyglotSourceCache.parseCached(PolyglotSourceCache.java:73)
	at com.oracle.truffle.polyglot.PolyglotLanguageContext.parseCached(PolyglotLanguageContext.java:321)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:820)
	at org.graalvm.polyglot.Context.eval(Context.java:344)
	at ninja.soroosh.hashem.lang.launcher.HashemiMain.executeSource(HashemiMain.java:65)
	at ninja.soroosh.hashem.lang.launcher.HashemiMain.main(HashemiMain.java:46)
Caused by: Attached Guest Language Frames (0)
```

**Comment by psycho-ir** [comment]
Hi @yasharrashedi, 
Thank for opening this issue.
Right version 0.02 didn't have `%` operator.
The new version which we released today should be bale to run your code!
https://github.com/psycho-ir/mr-hashemi/releases/tag/0.03

**Comment by yasharrashedi** [comment]
@psycho-ir thank you. I updated to the latest version and problem is solved.
